#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Cassandra::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant VERSION => "19.30.0";

1;
